-- Cambio a la base de datos enchufable
ALTER SESSION SET CONTAINER = XEPDB1;

-- 0. Limpieza previa de tablas simulando "IF EXISTS" (CASCADE CONSTRAINTS borra también las dependencias)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE prestamos CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE libros CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lectores CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE productos CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Definición del esquema
CREATE TABLE lectores (dni VARCHAR2(15) PRIMARY KEY, nombre VARCHAR2(50));
CREATE TABLE libros (isbn VARCHAR2(20) PRIMARY KEY, titulo VARCHAR2(100));
CREATE TABLE prestamos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni_lector VARCHAR2(15) REFERENCES lectores(dni),
    isbn_libro VARCHAR2(20) REFERENCES libros(isbn),
    fecha_prestamo DATE
);
CREATE TABLE productos (id NUMBER, nombre VARCHAR2(50));

-- 2. Inserción de catálogo base
INSERT INTO lectores VALUES ('12345678A', 'Laura Gómez');
INSERT INTO libros VALUES ('978-84', 'Cien años de soledad');
INSERT INTO libros VALUES ('978-99', 'El Quijote');
INSERT INTO productos VALUES (1, 'Monitor 4K');
COMMIT;

-- 3. Estrategia PL/SQL: Generación masiva de 500 préstamos
BEGIN
    FOR i IN 1..500 LOOP
        INSERT INTO prestamos (dni_lector, isbn_libro, fecha_prestamo) 
        VALUES (
            '12345678A', 
            CASE ROUND(DBMS_RANDOM.VALUE(1,2)) WHEN 1 THEN '978-84' ELSE '978-99' END,
            SYSDATE - ROUND(DBMS_RANDOM.VALUE(1, 30))
        );
    END LOOP;
    COMMIT;
END;
/

-- 4. Asignación de permisos de lectura para que el consultor pueda hacer SELECTs
GRANT SELECT ON productos TO rol_lectura;
GRANT SELECT ON lectores TO rol_lectura;
GRANT SELECT ON libros TO rol_lectura;
GRANT SELECT ON prestamos TO rol_lectura;