-- ==============================================================================
-- 02_seguridad_y_roles.sql (Db2)  -- Terminador: @
-- Ejecutar con: db2 -td@ -vf 02_seguridad_y_roles.sql
-- ==============================================================================

CONNECT TO PRACTDB2@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  EXECUTE IMMEDIATE 'DROP ROLE ROL_LECTURA';
END
@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  EXECUTE IMMEDIATE 'DROP ROLE ROL_ESCRITURA';
END
@

CREATE ROLE ROL_LECTURA
@

CREATE ROLE ROL_ESCRITURA
@

GRANT CONNECT ON DATABASE TO ROLE ROL_LECTURA
@

GRANT CONNECT ON DATABASE TO ROLE ROL_ESCRITURA
@

GRANT DATAACCESS ON DATABASE TO ROLE ROL_ESCRITURA
@

GRANT DBADM ON DATABASE TO ROLE ROL_ESCRITURA
@

REVOKE DATAACCESS ON DATABASE FROM ROLE ROL_LECTURA
@

GRANT ROLE ROL_LECTURA TO USER CONSULTOR
@

GRANT ROLE ROL_ESCRITURA TO USER EDITOR
@

TERMINATE
@
